//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrdersCollector.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznany błąd.
        /// </summary>
        public static string E_00000 {
            get {
                return ResourceManager.GetString("E_00000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznana komenda.
        /// </summary>
        public static string E_00001 {
            get {
                return ResourceManager.GetString("E_00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd składni.
        /// </summary>
        public static string E_00002 {
            get {
                return ResourceManager.GetString("E_00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędny format parametru..
        /// </summary>
        public static string E_00003 {
            get {
                return ResourceManager.GetString("E_00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznany dostawca.
        /// </summary>
        public static string E_00100 {
            get {
                return ResourceManager.GetString("E_00100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostawca o danej nazwie już istnieje.
        /// </summary>
        public static string E_00101 {
            get {
                return ResourceManager.GetString("E_00101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zamówień do dostawcy &apos;{0}&apos;.
        /// </summary>
        public static string E_00200 {
            get {
                return ResourceManager.GetString("E_00200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak pozycji zamówienia do usunięcia..
        /// </summary>
        public static string E_00400 {
            get {
                return ResourceManager.GetString("E_00400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto już istnieje w systemie..
        /// </summary>
        public static string E_00500 {
            get {
                return ResourceManager.GetString("E_00500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak konta o podanej nazwie..
        /// </summary>
        public static string E_00501 {
            get {
                return ResourceManager.GetString("E_00501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny kod aktywacyjny.
        /// </summary>
        public static string E_00502 {
            get {
                return ResourceManager.GetString("E_00502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o takiej nazwie istnieje..
        /// </summary>
        public static string E_00503 {
            get {
                return ResourceManager.GetString("E_00503", resourceCulture);
            }
        }
    }
}
