//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrdersCollector.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrdersCollector
        ///
        ///Lista dostępnych komend:
        ///- &quot;[{dostawca}] {treść zamówienia}&quot; - dodanie zamówienia dostawcy
        ///- &quot;#dodaj {dostawca}, {użytkownik}, {treść zamówienia}&quot; - dodanie zamówienia w imieniu innego użytkownika
        ///- &quot;#nowyDostawca {dostawca}&quot; - dodanie nowego dostawcy
        ///- &quot;#losuj {dostawca}&quot; - losowanie operatora zamówienia
        ///- &quot;#losujOsobe&quot; - losowanie osoby wśród wszystkich zamawiających
        ///- &quot;#losujOsobe {dostawca}&quot; - losowanie wśród osób zamawiających u dostawcy
        ///- &quot;#usunMojeZam {dostawca}&quot; - usuwanie  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpInfo {
            get {
                return ResourceManager.GetString("HelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator: {0}.
        /// </summary>
        public static string OperatorFormat {
            get {
                return ResourceManager.GetString("OperatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utw. zam. &apos;{0}&apos;.
        /// </summary>
        public static string OrderCreated {
            get {
                return ResourceManager.GetString("OrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienie z dnia {0}
        ///
        ///Dostawca: **{1}**
        ///
        ///{5}{2}
        ///
        ///Pozycje:
        ///
        ///{3}
        ///
        ///Razem: {4}.
        /// </summary>
        public static string OrderFormat {
            get {
                return ResourceManager.GetString("OrderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{2}&apos; -&gt; &apos;{0}&apos;.
        /// </summary>
        public static string OrderItemCreated {
            get {
                return ResourceManager.GetString("OrderItemCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięto pozycję &apos;{0}&apos; z zamówienia do &apos;{1}&apos; użytkownika &apos;{2}&apos;.
        /// </summary>
        public static string OrderItemDeleted {
            get {
                return ResourceManager.GetString("OrderItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon: {0}.
        /// </summary>
        public static string PhoneFormat {
            get {
                return ResourceManager.GetString("PhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak osób do losowania..
        /// </summary>
        public static string RandomNoUsers {
            get {
                return ResourceManager.GetString("RandomNoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatorem zamówienia do &apos;{0}&apos;  z dnia {1}  zostaje **{2}**. Dokonano losowania wśród ({3})..
        /// </summary>
        public static string RandomOperatorForOrder {
            get {
                return ResourceManager.GetString("RandomOperatorForOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wylosowano **{0}** wśród ({1})..
        /// </summary>
        public static string RandomUserActiveOrders {
            get {
                return ResourceManager.GetString("RandomUserActiveOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wylosowano **{0}** wśród zamawiających do &apos;{1}&apos; z dnia {2} ({3})..
        /// </summary>
        public static string RandomUserForOrder {
            get {
                return ResourceManager.GetString("RandomUserForOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy dostawca: &apos;{0}&apos;.
        /// </summary>
        public static string SupplierAdded {
            get {
                return ResourceManager.GetString("SupplierAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista dostawców:
        ///{0}.
        /// </summary>
        public static string SuppliersList {
            get {
                return ResourceManager.GetString("SuppliersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrdersCollector v{0} - https://github.com/jmansar/orders-collector.
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
    }
}
